using Cyqwel.Dialects;

namespace Cyqwel.Tests;

// Regenerated through Polyglot at 7c4f1f2 from SQLGlot v30.12.0; T-SQL cases are a supported static subset.
public partial class DialectIdentityFixtureTests
{
    [InlineData("tsql-identity-1", "SELECT TOP (SELECT 1) * FROM t")]
    [InlineData("tsql-identity-2", "SELECT ATN2(x, y)")]
    [InlineData("tsql-identity-3", "SELECT EXP(1)")]
    [InlineData("tsql-identity-4", "SELECT SYSDATETIMEOFFSET()")]
    [InlineData("tsql-identity-5", "SELECT COMPRESS('Hello World')")]
    [InlineData("tsql-identity-7", "DROP view a.b.c")]
    [InlineData("tsql-identity-10", "SELECT TRIM('     test    ') AS Result")]
    [InlineData("tsql-identity-15", "SELECT CONCAT(column1, column2)")]
    [InlineData("tsql-identity-19", "SELECT TestSpecialChar.Test_ FROM TestSpecialChar")]
    [InlineData("tsql-identity-20", "SELECT TOP (2 + 1) 1")]
    [InlineData("tsql-identity-21", "SELECT * FROM t WHERE NOT c")]
    [InlineData("tsql-identity-25", "WITH t1 AS (SELECT 1 AS a), t2 AS (SELECT 1 AS a) SELECT TOP 10 a FROM t1 UNION ALL SELECT TOP 10 a FROM t2")]
    [InlineData("tsql-identity-31", "WITH t1 AS (SELECT 1 AS a), t2 AS (SELECT 1 AS a) SELECT TOP 10 a FROM t1 UNION ALL SELECT TOP 10 a FROM t2 ORDER BY a DESC")]
    [InlineData("tsql-identity-32", "WITH t1 AS (SELECT 1 AS a), t2 AS (SELECT 1 AS a) SELECT COUNT(*) FROM (SELECT TOP 10 a FROM t1 UNION ALL SELECT TOP 10 a FROM t2 ORDER BY a DESC) AS t")]
    [InlineData("tsql-identity-33", "SELECT 1 AS \"[x]\"")]
    [InlineData("tsql-identity-34", "INSERT INTO foo.bar WITH cte AS (SELECT 1 AS one) SELECT * FROM cte")]
    [InlineData("tsql-identity-36", "CREATE TABLE x (A INTEGER NOT NULL, B INTEGER NULL)")]
    [InlineData("tsql-identity-38", "CREATE TABLE [db].[tbl]([a] [int])")]
    [InlineData("tsql-identity-48", "SELECT CASE WHEN a > 1 THEN b END")]
    [InlineData("tsql-identity-49", "SELECT * FROM taxi ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY")]
    [InlineData("tsql-identity-58", "SELECT a = 1")]
    [InlineData("tsql-identity-60", "SELECT a = 1 UNION ALL SELECT a = b")]
    [InlineData("tsql-identity-62", "SELECT DISTINCT DepartmentName, PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY BaseRate) OVER (PARTITION BY DepartmentName) AS MedianCont FROM dbo.DimEmployee")]
    [InlineData("tsql-identity-63", "SELECT \"x\".\"y\" FROM foo")]
    [InlineData("tsql-identity-91", "CREATE VIEW t AS WITH cte AS (SELECT 1 AS c) SELECT c FROM cte")]
    [InlineData("tsql-identity-140", "SELECT CAST(SUBSTRING('ABCD~1234', CHARINDEX('~', 'ABCD~1234') + 1, LEN('ABCD~1234')) AS BIGINT)")]
    [InlineData("tsql-identity-143", "SELECT DATEPART(\"dd\", x)")]
    [InlineData("tsql-identity-144", "SELECT DATEADD(YEAR, 1, '2017/08/25')")]
    [InlineData("tsql-identity-145", "SELECT DATEDIFF(HOUR, 1.5, '2021-01-01')")]
    [InlineData("tsql-identity-146", "SELECT DATEDIFF_BIG(HOUR, 1.5, '2021-01-01')")]
    [InlineData("tsql-identity-150", "SELECT FORMAT(foo, 'dddd', 'de-CH')")]
    [InlineData("tsql-identity-151", "SELECT FORMAT(EndOfDayRate, 'N', 'en-us')")]
    [InlineData("tsql-identity-152", "SELECT FORMAT('01-01-1991', 'd.mm.yyyy')")]
    [InlineData("tsql-identity-153", "SELECT FORMAT(12345, '###.###.###')")]
    [InlineData("tsql-identity-154", "SELECT FORMAT(1234567, 'f')")]
    [InlineData("tsql-identity-169", "WITH t AS (SELECT 1) SELECT * FROM t")]
    [InlineData("tsql-identity-170", "WITH t AS (SELECT \"c\") SELECT * FROM t")]
    [InlineData("tsql-identity-171", "SELECT * FROM (SELECT 1) AS subq")]
    [InlineData("tsql-identity-172", "SELECT * FROM (SELECT \"c\") AS subq")]
    [InlineData("tsql-identity-195", "SELECT COUNT(1) FROM x")]
    [InlineData("tsql-identity-196", "SELECT COUNT_BIG(1) FROM x")]
    [InlineData("tsql-identity-199", "SELECT 1; SELECT 2")]
    [InlineData("tsql-identity-201", "SELECT go")]
    [InlineData("tsql-identity-202", "SELECT 1 WHERE EXISTS(SELECT 1)")]
    [InlineData("tsql-identity-204", "ALTER TABLE dbo.DocExe DROP CONSTRAINT FK_Column_B")]
    [InlineData("tsql-identity-205", "SELECT a = 1")]
    [InlineData("tsql-identity-206", "SELECT * FROM [#temp_table]")]
    [InlineData("tsql-identity-207", "SELECT * FROM [##temp_table]")]
    [Theory]
    public void TSql_parse_generate_parse_is_stable(string caseName, string sql) =>
        AssertStable(SqlDialects.TSql, caseName, sql);
}
