using Cyqwel.Dialects;

namespace Cyqwel.Tests;

// Regenerated through Polyglot at 7c4f1f2 from SQLGlot v30.12.0; Generic cases are a supported static subset.
public partial class DialectIdentityFixtureTests
{
    [InlineData("generic-dialect-identity-1", "SELECT ARRAY_INTERSECT(x, y, z)")]
    [InlineData("generic-dialect-identity-11", "TRUNCATE TABLE db.schema.test")]
    [InlineData("generic-dialect-identity-13", "TRUNCATE TABLE t1, t2, t3")]
    [InlineData("generic-dialect-identity-14", "CREATE SEQUENCE seq")]
    [InlineData("generic-dialect-identity-29", "SELECT operator FROM t")]
    [InlineData("generic-identity-line-79", "SELECT call.x")]
    [InlineData("generic-identity-line-154", "SELECT asof FROM x")]
    [InlineData("generic-identity-line-214", "SELECT * FROM test")]
    [InlineData("generic-identity-line-216", "SELECT *, 1 FROM test")]
    [InlineData("generic-identity-line-217", "SELECT * FROM a.b")]
    [InlineData("generic-identity-line-218", "SELECT * FROM a.b.c")]
    [InlineData("generic-identity-line-220", "SELECT 1")]
    [InlineData("generic-identity-line-221", "SELECT 1 FROM test")]
    [InlineData("generic-identity-line-222", "SELECT * FROM a, b, (SELECT 1) AS c")]
    [InlineData("generic-identity-line-223", "SELECT a FROM test")]
    [InlineData("generic-identity-line-225", "SELECT 1 AS \"quoted alias\"")]
    [InlineData("generic-identity-line-228", "SELECT 1 AS count FROM test")]
    [InlineData("generic-identity-line-229", "SELECT 1 AS comment FROM test")]
    [InlineData("generic-identity-line-230", "SELECT 1 AS numeric FROM test")]
    [InlineData("generic-identity-line-231", "SELECT 1 AS number FROM test")]
    [InlineData("generic-identity-line-233", "SELECT t.count")]
    [InlineData("generic-identity-line-234", "SELECT DISTINCT x FROM test")]
    [InlineData("generic-identity-line-235", "SELECT DISTINCT x, y FROM test")]
    [InlineData("generic-identity-line-236", "SELECT DISTINCT TIMESTAMP_TRUNC(time_field, MONTH) AS time_value FROM \"table\"")]
    [InlineData("generic-identity-line-240", "SELECT DISTINCT FROM_SOMETHING")]
    [InlineData("generic-identity-line-242", "SELECT TIMESTAMP(DATE_TRUNC('MONTH', DATE(time_field))) AS time_value FROM \"table\"")]
    [InlineData("generic-identity-line-243", "SELECT GREATEST((3 + 1), LEAST(3, 4))")]
    [InlineData("generic-identity-line-246", "SELECT COUNT(DISTINCT a, b)")]
    [InlineData("generic-identity-line-247", "SELECT COUNT(DISTINCT a, b + 1)")]
    [InlineData("generic-identity-line-248", "SELECT SUM(DISTINCT x)")]
    [InlineData("generic-identity-line-249", "SELECT TRUNC(a, b)")]
    [InlineData("generic-identity-line-251", "SELECT LAG(x) OVER (ORDER BY y) AS x")]
    [InlineData("generic-identity-line-252", "SELECT LEAD(a) OVER (ORDER BY b) AS a")]
    [InlineData("generic-identity-line-253", "SELECT LEAD(a, 1) OVER (PARTITION BY a ORDER BY a) AS x")]
    [InlineData("generic-identity-line-254", "SELECT LEAD(a, 1, b) OVER (PARTITION BY a ORDER BY a) AS x")]
    [InlineData("generic-identity-line-257", "SELECT test.* FROM test")]
    [InlineData("generic-identity-line-258", "SELECT a AS b FROM test")]
    [InlineData("generic-identity-line-259", "SELECT \"a\".\"b\" FROM \"a\"")]
    [InlineData("generic-identity-line-260", "SELECT \"a\".b FROM a")]
    [InlineData("generic-identity-line-261", "SELECT a.b FROM \"a\"")]
    [InlineData("generic-identity-line-262", "SELECT a.b FROM a")]
    [InlineData("generic-identity-line-263", "SELECT '\"hi' AS x FROM x")]
    [InlineData("generic-identity-line-264", "SELECT 1 AS \"|sum\" FROM x")]
    [InlineData("generic-identity-line-265", "SELECT '\\\"hi' AS x FROM x")]
    [InlineData("generic-identity-line-266", "SELECT 1 AS b FROM test")]
    [InlineData("generic-identity-line-267", "SELECT 1 AS \"b\" FROM test")]
    [InlineData("generic-identity-line-268", "SELECT 1 + 1 FROM test")]
    [InlineData("generic-identity-line-269", "SELECT 1 - 1 FROM test")]
    [InlineData("generic-identity-line-270", "SELECT 1 * 1 FROM test")]
    [InlineData("generic-identity-line-271", "SELECT 1 % 1 FROM test")]
    [InlineData("generic-identity-line-272", "SELECT 1 / 1 FROM test")]
    [InlineData("generic-identity-line-273", "SELECT 1 < 2 FROM test")]
    [InlineData("generic-identity-line-274", "SELECT 1 <= 2 FROM test")]
    [InlineData("generic-identity-line-275", "SELECT 1 > 2 FROM test")]
    [InlineData("generic-identity-line-276", "SELECT 1 >= 2 FROM test")]
    [InlineData("generic-identity-line-277", "SELECT 1 <> 2 FROM test")]
    [InlineData("generic-identity-line-278", "SELECT JSON_EXTRACT(x, '$.name')")]
    [InlineData("generic-identity-line-279", "SELECT JSON_EXTRACT_SCALAR(x, '$.name')")]
    [InlineData("generic-identity-line-280", "SELECT x LIKE '%x%' FROM test")]
    [InlineData("generic-identity-line-281", "SELECT * FROM test LIMIT 100")]
    [InlineData("generic-identity-line-282", "SELECT * FROM test LIMIT 1 + 1")]
    [InlineData("generic-identity-line-283", "SELECT * FROM test LIMIT 100 OFFSET 200")]
    [InlineData("generic-identity-line-284", "SELECT * FROM test LIMIT (SELECT 1)")]
    [InlineData("generic-identity-line-285", "SELECT * FROM test LIMIT (SELECT 1) OFFSET (SELECT 1)")]
    [InlineData("generic-identity-line-287", "SELECT * FROM test FETCH FIRST 1 ROWS ONLY")]
    [InlineData("generic-identity-line-291", "SELECT * FROM test FETCH NEXT 1 ROWS ONLY")]
    [InlineData("generic-identity-line-292", "SELECT (1 > 2) AS x FROM test")]
    [InlineData("generic-identity-line-293", "SELECT NOT (1 > 2) FROM test")]
    [InlineData("generic-identity-line-294", "SELECT 1 + 2 AS x FROM test")]
    [InlineData("generic-identity-line-295", "SELECT a, b, 1 < 1 FROM test")]
    [InlineData("generic-identity-line-296", "SELECT a FROM test WHERE NOT FALSE")]
    [InlineData("generic-identity-line-297", "SELECT a FROM test WHERE a = 1")]
    [InlineData("generic-identity-line-298", "SELECT a FROM test WHERE a = 1 AND b = 2")]
    [InlineData("generic-identity-line-299", "SELECT a FROM test WHERE a IN (SELECT b FROM z)")]
    [InlineData("generic-identity-line-300", "SELECT a FROM test WHERE a IN ((SELECT 1), 2)")]
    [InlineData("generic-identity-line-302", "SELECT * FROM x WHERE y IN (SELECT 1 UNION SELECT 2)")]
    [InlineData("generic-identity-line-303", "SELECT * FROM x WHERE y IN ((SELECT 1 UNION SELECT 2))")]
    [InlineData("generic-identity-line-304", "SELECT * FROM x WHERE y IN (WITH z AS (SELECT 1) SELECT * FROM z)")]
    [InlineData("generic-identity-line-305", "SELECT a FROM test WHERE (a > 1)")]
    [InlineData("generic-identity-line-306", "SELECT a FROM test WHERE a > (SELECT 1 FROM x GROUP BY y)")]
    [InlineData("generic-identity-line-307", "SELECT a FROM test WHERE EXISTS(SELECT 1)")]
    [InlineData("generic-identity-line-308", "SELECT a FROM test WHERE EXISTS(SELECT * FROM x UNION SELECT * FROM Y) OR TRUE")]
    [InlineData("generic-identity-line-309", "SELECT a FROM test WHERE TRUE OR NOT EXISTS(SELECT * FROM x)")]
    [InlineData("generic-identity-line-314", "SELECT a FROM test ORDER BY a")]
    [InlineData("generic-identity-line-315", "SELECT a FROM test ORDER BY a, b")]
    [InlineData("generic-identity-line-316", "SELECT x FROM tests ORDER BY a DESC, b DESC, c")]
    [InlineData("generic-identity-line-317", "SELECT a FROM test ORDER BY a > 1")]
    [InlineData("generic-identity-line-318", "SELECT * FROM test ORDER BY DATE DESC, TIMESTAMP DESC")]
    [InlineData("generic-identity-line-319", "SELECT a, b FROM test GROUP BY 1")]
    [InlineData("generic-identity-line-320", "SELECT a, b FROM test GROUP BY a")]
    [InlineData("generic-identity-line-321", "SELECT a, b FROM test WHERE a = 1 GROUP BY a HAVING a = 2")]
    [InlineData("generic-identity-line-322", "SELECT a, b FROM test WHERE a = 1 GROUP BY a HAVING a = 2 ORDER BY a")]
    [InlineData("generic-identity-line-327", "SELECT a FROM test GROUP BY CUBE (x)")]
    [InlineData("generic-identity-line-328", "SELECT a FROM test GROUP BY ROLLUP (x)")]
    [InlineData("generic-identity-line-329", "SELECT t.a FROM test AS t GROUP BY ROLLUP (t.x)")]
    [InlineData("generic-identity-line-331", "SELECT a FROM test GROUP BY CUBE (x), ROLLUP (x, y, z)")]
    [InlineData("generic-identity-line-332", "SELECT CASE WHEN a < b THEN 1 WHEN a < c THEN 2 ELSE 3 END FROM test")]
    [InlineData("generic-identity-line-340", "SELECT a FROM (SELECT a FROM test) AS x")]
    [InlineData("generic-identity-line-341", "SELECT a FROM (SELECT a FROM (SELECT a FROM test) AS y) AS x")]
    [InlineData("generic-identity-line-342", "SELECT a FROM test WHERE a IN (1, 2, 3) OR b BETWEEN 1 AND 4")]
    [InlineData("generic-identity-line-356", "SELECT ABS(a) FROM test")]
    [InlineData("generic-identity-line-357", "SELECT AVG(a) FROM test")]
    [InlineData("generic-identity-line-358", "SELECT CEIL(a) FROM test")]
    [InlineData("generic-identity-line-359", "SELECT CEIL(a, b) FROM test")]
    [InlineData("generic-identity-line-360", "SELECT COUNT(a) FROM test")]
    [InlineData("generic-identity-line-361", "SELECT COUNT(1) FROM test")]
    [InlineData("generic-identity-line-362", "SELECT COUNT(*) FROM test")]
    [InlineData("generic-identity-line-363", "SELECT COUNT() FROM test")]
    [InlineData("generic-identity-line-364", "SELECT COUNT(DISTINCT a) FROM test")]
    [InlineData("generic-identity-line-365", "SELECT EXP(a) FROM test")]
    [InlineData("generic-identity-line-366", "SELECT FLOOR(a) FROM test")]
    [InlineData("generic-identity-line-367", "SELECT FLOOR(a, b) FROM test")]
    [InlineData("generic-identity-line-368", "SELECT FIRST_VALUE(a) FROM test")]
    [InlineData("generic-identity-line-369", "SELECT GREATEST(a, b, c) FROM test")]
    [InlineData("generic-identity-line-370", "SELECT LAST_VALUE(a) FROM test")]
    [InlineData("generic-identity-line-372", "SELECT LN(a) FROM test")]
    [InlineData("generic-identity-line-373", "SELECT MAX(a) FROM test")]
    [InlineData("generic-identity-line-374", "SELECT MIN(a) FROM test")]
    [InlineData("generic-identity-line-375", "SELECT POWER(a, 2) FROM test")]
    [InlineData("generic-identity-line-376", "SELECT QUANTILE(a, 0.95) FROM test")]
    [InlineData("generic-identity-line-377", "SELECT ROUND(a) FROM test")]
    [InlineData("generic-identity-line-378", "SELECT ROUND(a, 2) FROM test")]
    [InlineData("generic-identity-line-379", "SELECT SUM(a) FROM test")]
    [InlineData("generic-identity-line-380", "SELECT SQRT(a) FROM test")]
    [InlineData("generic-identity-line-381", "SELECT STDDEV(a) FROM test")]
    [InlineData("generic-identity-line-382", "SELECT STDDEV_POP(a) FROM test")]
    [InlineData("generic-identity-line-383", "SELECT STDDEV_SAMP(a) FROM test")]
    [InlineData("generic-identity-line-384", "SELECT VARIANCE(a) FROM test")]
    [InlineData("generic-identity-line-385", "SELECT VARIANCE_POP(a) FROM test")]
    [InlineData("generic-identity-line-386", "SELECT CAST(a AS INT) FROM test")]
    [InlineData("generic-identity-line-387", "SELECT CAST(a AS DATETIME) FROM test")]
    [InlineData("generic-identity-line-388", "SELECT CAST(a AS VARCHAR) FROM test")]
    [InlineData("generic-identity-line-389", "SELECT CAST(a < 1 AS INT) FROM test")]
    [InlineData("generic-identity-line-390", "SELECT CAST(a IS NULL AS INT) FROM test")]
    [InlineData("generic-identity-line-391", "SELECT COUNT(CAST(1 < 2 AS INT)) FROM test")]
    [InlineData("generic-identity-line-392", "SELECT COUNT(CASE WHEN CAST(1 < 2 AS BOOLEAN) THEN 1 END) FROM test")]
    [InlineData("generic-identity-line-393", "SELECT CAST(a AS DECIMAL) FROM test")]
    [InlineData("generic-identity-line-394", "SELECT CAST(a AS DECIMAL(1)) FROM test")]
    [InlineData("generic-identity-line-395", "SELECT CAST(a AS DECIMAL(1, 2)) FROM test")]
    [InlineData("generic-identity-line-397", "SELECT CAST(a AS TIMESTAMP) FROM test")]
    [InlineData("generic-identity-line-398", "SELECT CAST(a AS DATE) FROM test")]
    [InlineData("generic-identity-line-400", "SELECT CAST(a AS VARIANT) FROM test")]
    [InlineData("generic-identity-line-401", "SELECT TRY_CAST(a AS INT) FROM test")]
    [InlineData("generic-identity-line-402", "SELECT COALESCE(a, b, c) FROM test")]
    [InlineData("generic-identity-line-403", "SELECT ANY_VALUE(a) FROM test")]
    [InlineData("generic-identity-line-404", "SELECT 1 FROM a JOIN b ON a.x = b.x")]
    [InlineData("generic-identity-line-405", "SELECT 1 FROM a JOIN b AS c ON a.x = b.x")]
    [InlineData("generic-identity-line-406", "SELECT 1 FROM a INNER JOIN b ON a.x = b.x")]
    [InlineData("generic-identity-line-407", "SELECT 1 FROM a LEFT JOIN b ON a.x = b.x")]
    [InlineData("generic-identity-line-408", "SELECT 1 FROM a RIGHT JOIN b ON a.x = b.x")]
    [InlineData("generic-identity-line-409", "SELECT 1 FROM a CROSS JOIN b ON a.x = b.x")]
    [InlineData("generic-identity-line-410", "SELECT 1 FROM a SEMI JOIN b ON a.x = b.x")]
    [InlineData("generic-identity-line-415", "SELECT 1 FROM a JOIN b USING (x)")]
    [InlineData("generic-identity-line-416", "SELECT 1 FROM a JOIN b USING (x, y, z)")]
    [InlineData("generic-identity-line-417", "SELECT 1 FROM a JOIN (SELECT a FROM c) AS b ON a.x = b.x AND a.x < 2")]
    [InlineData("generic-identity-line-418", "SELECT 1 FROM a UNION SELECT 2 FROM b")]
    [InlineData("generic-identity-line-419", "SELECT 1 FROM a UNION ALL SELECT 2 FROM b")]
    [InlineData("generic-identity-line-420", "SELECT 1 FROM a JOIN b ON a.foo = b.bar JOIN c ON a.foo = c.bar")]
    [InlineData("generic-identity-line-421", "SELECT 1 FROM a LEFT JOIN b ON a.foo = b.bar JOIN c ON a.foo = c.bar")]
    [InlineData("generic-identity-line-423", "SELECT 1 FROM a LEFT OUTER JOIN b ON a.foo = b.bar")]
    [InlineData("generic-identity-line-424", "SELECT 1 FROM a NATURAL JOIN b")]
    [InlineData("generic-identity-line-425", "SELECT 1 FROM a NATURAL LEFT JOIN b")]
    [InlineData("generic-identity-line-426", "SELECT 1 FROM a NATURAL LEFT OUTER JOIN b")]
    [InlineData("generic-identity-line-428", "SELECT 1 FROM a FULL JOIN b ON a.foo = b.bar")]
    [InlineData("generic-identity-line-431", "SELECT 1 UNION ALL SELECT 2")]
    [InlineData("generic-identity-line-432", "SELECT 1 EXCEPT SELECT 2")]
    [InlineData("generic-identity-line-433", "SELECT 1 EXCEPT SELECT 2")]
    [InlineData("generic-identity-line-434", "SELECT 1 INTERSECT SELECT 2")]
    [InlineData("generic-identity-line-435", "SELECT 1 INTERSECT SELECT 2")]
    [InlineData("generic-identity-line-442", "SELECT * FROM (SELECT 1) AS x")]
    [InlineData("generic-identity-line-443", "SELECT * FROM (SELECT 1 UNION SELECT 2) AS x")]
    [InlineData("generic-identity-line-444", "SELECT * FROM (SELECT 1 UNION ALL SELECT 2) AS x")]
    [InlineData("generic-identity-line-469", "WITH a AS (SELECT 1) SELECT 1 UNION ALL SELECT 2")]
    [InlineData("generic-identity-line-470", "WITH a AS (SELECT 1) SELECT 1 UNION SELECT 2")]
    [InlineData("generic-identity-line-471", "WITH a AS (SELECT 1) SELECT 1 INTERSECT SELECT 2")]
    [InlineData("generic-identity-line-472", "WITH a AS (SELECT 1) SELECT 1 EXCEPT SELECT 2")]
    [InlineData("generic-identity-line-473", "WITH a AS (SELECT 1) SELECT 1 EXCEPT SELECT 2")]
    [InlineData("generic-identity-line-486", "VALUES (1) UNION SELECT * FROM x")]
    [InlineData("generic-identity-line-487", "WITH a AS (SELECT 1) SELECT a.* FROM a")]
    [InlineData("generic-identity-line-488", "WITH a AS (SELECT 1), b AS (SELECT 2) SELECT a.*, b.* FROM a CROSS JOIN b")]
    [InlineData("generic-identity-line-489", "WITH a AS (WITH b AS (SELECT 1 AS x) SELECT b.x FROM b) SELECT a.x FROM a")]
    [InlineData("generic-identity-line-490", "WITH RECURSIVE T(n) AS (VALUES (1) UNION ALL SELECT n + 1 FROM t WHERE n < 100) SELECT SUM(n) FROM t")]
    [InlineData("generic-identity-line-491", "WITH RECURSIVE T(n, m) AS (VALUES (1, 2) UNION ALL SELECT n + 1, n + 2 FROM t) SELECT SUM(n) FROM t")]
    [InlineData("generic-identity-line-493", "SELECT * FROM (WITH y AS (SELECT 1 AS z) SELECT z FROM y) AS x")]
    [InlineData("generic-identity-line-494", "SELECT RANK() OVER () FROM x")]
    [InlineData("generic-identity-line-495", "SELECT RANK() OVER () AS y FROM x")]
    [InlineData("generic-identity-line-496", "SELECT RANK() OVER (PARTITION BY a) FROM x")]
    [InlineData("generic-identity-line-497", "SELECT RANK() OVER (PARTITION BY a, b) FROM x")]
    [InlineData("generic-identity-line-498", "SELECT RANK() OVER (ORDER BY a) FROM x")]
    [InlineData("generic-identity-line-499", "SELECT RANK() OVER (ORDER BY a, b) FROM x")]
    [InlineData("generic-identity-line-500", "SELECT RANK() OVER (PARTITION BY a ORDER BY a) FROM x")]
    [InlineData("generic-identity-line-501", "SELECT RANK() OVER (PARTITION BY a, b ORDER BY a, b DESC) FROM x")]
    [InlineData("generic-identity-line-502", "SELECT SUM(x) OVER (PARTITION BY a) AS y FROM x")]
    [InlineData("generic-identity-line-503", "SELECT SUM(x) OVER (PARTITION BY a ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)")]
    [InlineData("generic-identity-line-504", "SELECT SUM(x) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)")]
    [InlineData("generic-identity-line-505", "SELECT SUM(x) OVER (PARTITION BY a ORDER BY b ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)")]
    [InlineData("generic-identity-line-506", "SELECT SUM(x) OVER (PARTITION BY a ORDER BY b RANGE BETWEEN INTERVAL '1' DAY PRECEDING AND CURRENT ROW)")]
    [InlineData("generic-identity-line-507", "SELECT SUM(x) OVER (PARTITION BY a ORDER BY b RANGE BETWEEN INTERVAL '1' DAY PRECEDING AND INTERVAL '2' DAYS FOLLOWING)")]
    [InlineData("generic-identity-line-508", "SELECT SUM(x) OVER (PARTITION BY a ORDER BY b RANGE BETWEEN INTERVAL '1' DAY PRECEDING AND UNBOUNDED FOLLOWING)")]
    [InlineData("generic-identity-line-510", "SELECT SUM(x) OVER (PARTITION BY a ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)")]
    [InlineData("generic-identity-line-511", "SELECT SUM(x) OVER (PARTITION BY a ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)")]
    [InlineData("generic-identity-line-512", "SELECT SUM(x) OVER (PARTITION BY a RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)")]
    [InlineData("generic-identity-line-515", "SELECT SUM(x) OVER (PARTITION BY a RANGE BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING)")]
    [InlineData("generic-identity-line-516", "SELECT AVG(x) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM t")]
    [InlineData("generic-identity-line-517", "SELECT SUM(x) OVER (PARTITION BY a ORDER BY date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)")]
    [InlineData("generic-identity-line-518", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY x) AS y")]
    [InlineData("generic-identity-line-519", "SELECT LISTAGG(x) WITHIN GROUP (ORDER BY x DESC)")]
    [InlineData("generic-identity-line-520", "SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY x)")]
    [InlineData("generic-identity-line-521", "SELECT PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY x)")]
    [InlineData("generic-identity-line-522", "SELECT SUM(x) FILTER(WHERE x > 1)")]
    [InlineData("generic-identity-line-523", "SELECT SUM(x) FILTER(WHERE x > 1) OVER (ORDER BY y)")]
    [InlineData("generic-identity-line-524", "SELECT COUNT(DISTINCT a) OVER (PARTITION BY c ORDER BY d ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)")]
    [InlineData("generic-identity-line-525", "SELECT a['1'], b[0], x.c[0], \"x\".d['1'] FROM x")]
    [InlineData("generic-identity-line-526", "SELECT ARRAY(1, 2, 3) FROM x")]
    [InlineData("generic-identity-line-527", "SELECT ARRAY(ARRAY(1), ARRAY(2)) FROM x")]
    [InlineData("generic-identity-line-528", "SELECT MAP[ARRAY(1), ARRAY(2)] FROM x")]
    [InlineData("generic-identity-line-529", "SELECT MAP(ARRAY(1), ARRAY(2)) FROM x")]
    [InlineData("generic-identity-line-530", "SELECT MAX(ARRAY(1, 2, 3)) FROM x")]
    [InlineData("generic-identity-line-547", "CREATE TABLE a.b AS SELECT 1")]
    [InlineData("generic-identity-line-553", "CREATE TABLE a.b AS SELECT a FROM a.c")]
    [InlineData("generic-identity-line-554", "CREATE TABLE IF NOT EXISTS x AS SELECT a FROM d")]
    [InlineData("generic-identity-line-555", "CREATE TABLE z (a INT, b VARCHAR, c VARCHAR(100), d DECIMAL(5, 3))")]
    [InlineData("generic-identity-line-557", "CREATE TABLE z (bucket INT)")]
    [InlineData("generic-identity-line-561", "CREATE TABLE z (a INT(11) DEFAULT UUID())")]
    [InlineData("generic-identity-line-562", "CREATE TABLE z (n INT DEFAULT 0 NOT NULL)")]
    [InlineData("generic-identity-line-564", "CREATE TABLE z (a INT(11) NOT NULL DEFAULT 1)")]
    [InlineData("generic-identity-line-565", "CREATE TABLE z (a INT(11) NOT NULL DEFAULT -1)")]
    [InlineData("generic-identity-line-567", "CREATE TABLE z (a INT, PRIMARY KEY (a))")]
    [InlineData("generic-identity-line-576", "CREATE TABLE z (a INT UNIQUE)")]
    [InlineData("generic-identity-line-581", "CREATE TABLE z (a INT, FOREIGN KEY (a) REFERENCES parent (b, c))")]
    [InlineData("generic-identity-line-592", "CREATE TABLE products (x INT GENERATED BY DEFAULT AS IDENTITY)")]
    [InlineData("generic-identity-line-594", "CREATE TABLE products (x INT GENERATED ALWAYS AS IDENTITY)")]
    [InlineData("generic-identity-line-600", "CREATE TABLE customer (period INT NOT NULL)")]
    [InlineData("generic-identity-line-605", "CREATE TABLE t (title TEXT)")]
    [InlineData("generic-identity-line-606", "CREATE TABLE foo (baz INT, inline TEXT)")]
    [InlineData("generic-identity-line-608", "CREATE TEMPORARY TABLE x AS SELECT a FROM d")]
    [InlineData("generic-identity-line-609", "CREATE TEMPORARY TABLE IF NOT EXISTS x AS SELECT a FROM d")]
    [InlineData("generic-identity-line-611", "CREATE VIEW x AS SELECT a FROM b")]
    [InlineData("generic-identity-line-615", "CREATE OR REPLACE VIEW x AS SELECT *")]
    [InlineData("generic-identity-line-616", "CREATE OR REPLACE TEMPORARY VIEW x AS SELECT *")]
    [InlineData("generic-identity-line-617", "CREATE TEMPORARY VIEW x AS SELECT a FROM d")]
    [InlineData("generic-identity-line-619", "CREATE TEMPORARY VIEW x AS WITH y AS (SELECT 1) SELECT * FROM y")]
    [InlineData("generic-identity-line-637", "CREATE INDEX abc ON t(a)")]
    [InlineData("generic-identity-line-638", "CREATE INDEX \"abc\" ON t(a)")]
    [InlineData("generic-identity-line-639", "CREATE INDEX abc ON t(a, b, b)")]
    [InlineData("generic-identity-line-640", "CREATE INDEX abc ON t(a NULLS LAST)")]
    [InlineData("generic-identity-line-642", "CREATE UNIQUE INDEX abc ON t(a, b, b)")]
    [InlineData("generic-identity-line-643", "CREATE UNIQUE INDEX IF NOT EXISTS my_idx ON tbl(a, b)")]
    [InlineData("generic-identity-line-654", "DROP INDEX a.b.c")]
    [InlineData("generic-identity-line-672", "DELETE FROM x WHERE y > 1")]
    [InlineData("generic-identity-line-673", "DELETE FROM y")]
    [InlineData("generic-identity-line-674", "DELETE FROM event USING sales WHERE event.eventid = sales.eventid")]
    [InlineData("generic-identity-line-675", "DELETE FROM event USING sales, bla WHERE event.eventid = sales.eventid")]
    [InlineData("generic-identity-line-676", "DELETE FROM event USING sales AS s WHERE event.eventid = s.eventid")]
    [InlineData("generic-identity-line-677", "DELETE FROM event AS event USING sales AS s WHERE event.eventid = s.eventid")]
    [InlineData("generic-identity-line-678", "DROP TABLE a")]
    [InlineData("generic-identity-line-679", "DROP TABLE a.b")]
    [InlineData("generic-identity-line-680", "DROP TABLE IF EXISTS a")]
    [InlineData("generic-identity-line-681", "DROP TABLE IF EXISTS a.b")]
    [InlineData("generic-identity-line-682", "DROP TABLE a CASCADE")]
    [InlineData("generic-identity-line-685", "DROP VIEW a")]
    [InlineData("generic-identity-line-686", "DROP VIEW a.b")]
    [InlineData("generic-identity-line-687", "DROP VIEW IF EXISTS a")]
    [InlineData("generic-identity-line-688", "DROP VIEW IF EXISTS a.b")]
    [InlineData("generic-identity-line-693", "INSERT INTO x SELECT * FROM y")]
    [InlineData("generic-identity-line-695", "INSERT INTO x WITH y AS (SELECT 1) SELECT * FROM y")]
    [InlineData("generic-identity-line-697", "INSERT INTO x VALUES (1, 'a', 2.0)")]
    [InlineData("generic-identity-line-699", "INSERT INTO y (a, b, c) SELECT a, b, c FROM x")]
    [InlineData("generic-identity-line-702", "INSERT INTO \"tests_user\" (\"username\", \"first_name\", \"last_name\") VALUES ('fiara', 'Fiara', 'Ironhide') RETURNING \"tests_user\".\"id\"")]
    [InlineData("generic-identity-line-703", "INSERT INTO t1 (tc1 /* tc1 */, tc2 /* tc2 */) SELECT c1 /* sc1 */, c2 /* sc2 */ FROM t")]
    [InlineData("generic-identity-line-704", "INSERT INTO t1 (\"tc1\" /* tc1 */, \"tc2\" /* tc2 */) SELECT \"c1\" /* sc1 */, \"c2\" /* sc2 */ FROM t")]
    [InlineData("generic-identity-line-719", "UPDATE tbl_name SET foo = 123")]
    [InlineData("generic-identity-line-720", "UPDATE tbl_name SET foo = 123, bar = 345")]
    [InlineData("generic-identity-line-721", "UPDATE db.tbl_name SET foo = 123 WHERE tbl_name.bar = 234")]
    [InlineData("generic-identity-line-722", "UPDATE db.tbl_name SET foo = 123, foo_1 = 234 WHERE tbl_name.bar = 234")]
    [InlineData("generic-identity-line-735", "SELECT :hello, ? FROM x LIMIT :my_limit")]
    [InlineData("generic-identity-line-740", "SELECT (WITH x AS (SELECT 1 AS y) SELECT * FROM x) AS z")]
    [InlineData("generic-identity-line-741", "SELECT ((SELECT 1) + 1)")]
    [InlineData("generic-identity-line-744", "SELECT * FROM project.dataset.INFORMATION_SCHEMA.TABLES")]
    [InlineData("generic-identity-line-745", "SELECT CAST(x AS INT) /* comment */ FROM foo")]
    [InlineData("generic-identity-line-746", "SELECT c /* c1 */ AS alias /* c2 */")]
    [InlineData("generic-identity-line-747", "SELECT a /* x */, b /* x */")]
    [InlineData("generic-identity-line-748", "SELECT a /* x */ /* y */ /* z */, b /* k */ /* m */")]
    [InlineData("generic-identity-line-749", "SELECT * FROM foo /* x */, bla /* x */")]
    [InlineData("generic-identity-line-750", "SELECT 1 /* comment */ + 1")]
    [InlineData("generic-identity-line-751", "SELECT 1 /* c1 */ + 2 /* c2 */")]
    [InlineData("generic-identity-line-752", "SELECT 1 /* c1 */ + /* c2 */ 2 /* c3 */")]
    [InlineData("generic-identity-line-753", "SELECT 1 /* c1 */ + 2 /* c2 */ + 3 /* c3 */")]
    [InlineData("generic-identity-line-754", "SELECT 1 /* c1 */ + 2 /* c2 */, 3 /* c3 */")]
    [InlineData("generic-identity-line-755", "SELECT x FROM a.b.c /* x */, e.f.g /* x */")]
    [InlineData("generic-identity-line-756", "SELECT FOO(x /* c */) /* FOO */, b /* b */")]
    [InlineData("generic-identity-line-758", "INSERT INTO foo SELECT * FROM bar /* comment */")]
    [InlineData("generic-identity-line-759", "/* c */ WITH x AS (SELECT 1) SELECT * FROM x")]
    [InlineData("generic-identity-line-762", "ALTER TABLE integers ADD COLUMN k INT")]
    [InlineData("generic-identity-line-767", "ALTER TABLE integers ADD COLUMN l INT DEFAULT 10")]
    [InlineData("generic-identity-line-768", "ALTER TABLE measurements ADD COLUMN mtime TIMESTAMPTZ DEFAULT NOW()")]
    [InlineData("generic-identity-line-769", "ALTER TABLE integers DROP COLUMN k")]
    [InlineData("generic-identity-line-770", "ALTER TABLE integers DROP COLUMN IF EXISTS k")]
    [InlineData("generic-identity-line-771", "ALTER TABLE integers DROP COLUMN k CASCADE")]
    [InlineData("generic-identity-line-774", "ALTER TABLE integers ALTER COLUMN i SET DEFAULT 10")]
    [InlineData("generic-identity-line-775", "ALTER TABLE integers ALTER COLUMN i DROP DEFAULT")]
    [InlineData("generic-identity-line-777", "ALTER TABLE mydataset.mytable DROP COLUMN A, DROP COLUMN IF EXISTS B")]
    [InlineData("generic-identity-line-783", "ALTER TABLE table1 RENAME COLUMN c1 TO c2")]
    [InlineData("generic-identity-line-785", "ALTER TABLE table1 RENAME TO table2")]
    [InlineData("generic-identity-line-789", "SELECT div.a FROM test_table AS div")]
    [InlineData("generic-identity-line-794", "ALTER TABLE \"schema\".\"tablename\" ADD CONSTRAINT \"CHK_Name\" CHECK (NOT \"IdDwh\" IS NULL AND \"IdDwh\" <> (0))")]
    [InlineData("generic-identity-line-795", "ALTER TABLE persons ADD CONSTRAINT persons_pk PRIMARY KEY (first_name, last_name)")]
    [InlineData("generic-identity-line-797", "ALTER TABLE pets ADD CONSTRAINT pets_name_not_cute_chk CHECK (LENGTH(name) < 20)")]
    [InlineData("generic-identity-line-798", "ALTER TABLE people10m ADD CONSTRAINT dateWithinRange CHECK (birthDate > '1900-01-01')")]
    [InlineData("generic-identity-line-807", "SELECT partition FROM a")]
    [InlineData("generic-identity-line-809", "SELECT id FROM b.a AS a QUALIFY ROW_NUMBER() OVER (PARTITION BY br ORDER BY sadf DESC) = 1")]
    [InlineData("generic-identity-line-840", "SELECT PERCENTILE_CONT(x, 0.5) OVER ()")]
    [InlineData("generic-identity-line-845", "SELECT * FROM current_date")]
    [InlineData("generic-identity-line-846", "SELECT * FROM schema.current_date")]
    [InlineData("generic-identity-line-847", "SELECT /*+ SOME_HINT(foo) */ 1")]
    [InlineData("generic-identity-line-848", "SELECT /*+ REBALANCE */ * FROM foo")]
    [InlineData("generic-identity-line-850", "/* comment1 */ INSERT INTO x /* comment2 */ VALUES (1, 2, 3)")]
    [InlineData("generic-identity-line-851", "/* comment1 */ UPDATE tbl /* comment2 */ SET x = 2 WHERE x < 2")]
    [InlineData("generic-identity-line-852", "/* comment1 */ DELETE FROM x /* comment2 */ WHERE y > 1")]
    [InlineData("generic-identity-line-853", "/* comment */ CREATE TABLE foo AS SELECT 1")]
    [InlineData("generic-identity-line-855", "SELECT \"any\", \"case\", \"if\", \"next\"")]
    [InlineData("generic-identity-line-856", "SELECT x FROM y ORDER BY x ASC")]
    [InlineData("generic-identity-line-862", "SELECT x FROM t1 UNION ALL SELECT x FROM t2 LIMIT 1")]
    [InlineData("generic-identity-line-863", "SELECT x FROM t1 UNION ALL SELECT x FROM t2 UNION ALL SELECT x FROM t3 LIMIT 1")]
    [InlineData("generic-identity-line-864", "WITH use(use) AS (SELECT 1) SELECT use FROM use")]
    [InlineData("generic-identity-line-866", "SELECT (ROW_NUMBER() OVER (PARTITION BY user ORDER BY date ASC) - ROW_NUMBER() OVER (PARTITION BY user, segment ORDER BY date ASC)) AS group_id FROM example_table")]
    [InlineData("generic-identity-line-874", "SELECT enum")]
    [InlineData("generic-identity-line-875", "SELECT unlogged")]
    [InlineData("generic-identity-line-876", "SELECT name")]
    [InlineData("generic-identity-line-877", "SELECT copy")]
    [InlineData("generic-identity-line-878", "SELECT rollup")]
    [InlineData("generic-identity-line-879", "SELECT unnest")]
    [InlineData("generic-identity-line-880", "SELECT cube, cube.x FROM cube")]
    [InlineData("generic-identity-line-882", "SELECT COUNT(DISTINCT \"foo bar\") FROM (SELECT 1 AS \"foo bar\") AS t")]
    [InlineData("generic-identity-line-883", "SELECT vector")]
    [InlineData("generic-identity-line-897", "SELECT attach")]
    [InlineData("generic-identity-line-898", "SELECT detach")]
    [InlineData("generic-identity-line-899", "SELECT 1 OFFSET 1")]
    [InlineData("generic-identity-line-900", "SELECT 1 LIMIT 1")]
    [InlineData("generic-identity-line-904", "SELECT export")]
    [InlineData("generic-identity-line-914", "SELECT ACOS(x)")]
    [InlineData("generic-identity-line-915", "SELECT ACOSH(x)")]
    [InlineData("generic-identity-line-916", "SELECT ASIN(x)")]
    [InlineData("generic-identity-line-917", "SELECT ASINH(x)")]
    [InlineData("generic-identity-line-918", "SELECT ATAN(x)")]
    [InlineData("generic-identity-line-919", "SELECT ATANH(x)")]
    [InlineData("generic-identity-line-920", "SELECT ATAN2(x, y)")]
    [InlineData("generic-identity-line-921", "SELECT COT(x)")]
    [InlineData("generic-identity-line-922", "SELECT COTH(x)")]
    [InlineData("generic-identity-line-923", "SELECT CSC(x)")]
    [InlineData("generic-identity-line-924", "SELECT CSCH(x)")]
    [InlineData("generic-identity-line-925", "SELECT RADIANS(x)")]
    [InlineData("generic-identity-line-926", "SELECT SEC(x)")]
    [InlineData("generic-identity-line-927", "SELECT SECH(x)")]
    [InlineData("generic-identity-line-928", "SELECT UTC_DATE")]
    [InlineData("generic-identity-line-929", "SELECT UTC_TIME")]
    [InlineData("generic-identity-line-930", "SELECT UTC_TIMESTAMP")]
    [InlineData("generic-identity-line-931", "SELECT SIN(x)")]
    [InlineData("generic-identity-line-932", "SELECT SINH(x)")]
    [InlineData("generic-identity-line-933", "SELECT TANH(x)")]
    [InlineData("generic-identity-line-934", "SELECT COSINE_DISTANCE(v1, v2)")]
    [InlineData("generic-identity-line-935", "SELECT EUCLIDEAN_DISTANCE(v1, v2)")]
    [InlineData("generic-identity-line-940", "SELECT lock")]
    [InlineData("generic-identity-line-944", "WITH UNNEST AS (SELECT 1 AS UNNEST) SELECT UNNEST FROM UNNEST")]
    [InlineData("generic-identity-line-949", "SELECT CURRENT_DATABASE()")]
    [InlineData("generic-identity-line-950", "SELECT CURRENT_SCHEMAS(arg_bool)")]
    [InlineData("generic-identity-line-951", "SELECT UNIFORM(1, 10, 5)")]
    [InlineData("generic-identity-line-952", "SELECT UNIFORM(1, 10)")]
    [InlineData("generic-identity-line-953", "SELECT CURRENT_TIMEZONE()")]
    [Theory]
    public void Generic_parse_generate_parse_is_stable(string caseName, string sql) =>
        AssertStable(SqlDialects.Generic, caseName, sql);
}
