using Cyqwel.Ast;
using Cyqwel.Dialects;
using Cyqwel.Parsing;
using Cyqwel.Visitors;
using Cyqwel.Validation;

namespace Cyqwel.Tests;

public class TSqlDdlCoreTests
{
    [Theory]
    [InlineData("CREATE SCHEMA testSchema")]
    [InlineData("CREATE SCHEMA [test schema]")]
    [InlineData("CREATE TABLE t (id INT IDENTITY PRIMARY KEY)")]
    [InlineData("CREATE TABLE t (id INT NOT NULL IDENTITY(10, -1) PRIMARY KEY, a INT CONSTRAINT df_a DEFAULT 0)")]
    [InlineData("CREATE TABLE t (id INT, CONSTRAINT pk PRIMARY KEY CLUSTERED (id DESC))")]
    [InlineData("CREATE TABLE t (id INT, UNIQUE NONCLUSTERED (id ASC))")]
    [InlineData("CREATE CLUSTERED INDEX ix ON t (id DESC)")]
    [InlineData("CREATE UNIQUE NONCLUSTERED INDEX ix ON t (id ASC) WHERE id > 0")]
    [InlineData("ALTER TABLE t ADD id INT IDENTITY(10, 1)")]
    [InlineData("ALTER TABLE t ALTER COLUMN id BIGINT NOT NULL")]
    [InlineData("ALTER TABLE a ALTER COLUMN b VARCHAR(10) COLLATE Latin1_General_CI_AS NOT NULL")]
    [InlineData("ALTER TABLE a ALTER COLUMN b CHAR(10) COLLATE abc")]
    [InlineData("ALTER TABLE t ADD CONSTRAINT df DEFAULT 0 FOR id")]
    [InlineData("ALTER TABLE t ADD a INT, b INT CONSTRAINT df DEFAULT 0, CONSTRAINT pk PRIMARY KEY (a)")]
    [InlineData("ALTER TABLE t ADD c AS (a + b) PERSISTED")]
    [InlineData("CREATE TABLE t (id INT CONSTRAINT fk REFERENCES other_t (id) ON DELETE CASCADE, a INT CONSTRAINT ck CHECK (a > 0))")]
    [InlineData("CREATE TABLE t (id INT, INDEX ix NONCLUSTERED (id DESC))")]
    [InlineData("DECLARE @MyTableVar TABLE (EmpID INT NOT NULL, PRIMARY KEY CLUSTERED (EmpID), UNIQUE NONCLUSTERED (EmpID), INDEX CustomNonClusteredIndex NONCLUSTERED (EmpID))")]
    [InlineData("ALTER TABLE t WITH CHECK ADD CONSTRAINT fk FOREIGN KEY (id) REFERENCES other_t (id)")]
    [InlineData("CREATE TABLE tbl (a AS (x + 1) PERSISTED, b AS (y + 2), c AS (y / 3) PERSISTED NOT NULL)")]
    [InlineData("ALTER VIEW v AS SELECT a FROM t")]
    [InlineData("CREATE OR ALTER VIEW dbo.v AS SELECT 1 AS a")]
    [InlineData("CREATE FUNCTION foo(@bar INTEGER) RETURNS TABLE AS RETURN SELECT 1 AS a")]
    [InlineData("CREATE FUNCTION dbo.f() RETURNS TABLE AS RETURN (WITH subquery AS (SELECT id AS id FROM subtable) SELECT other_id FROM main_table AS mt INNER JOIN subquery ON subquery.id = mt.other_id)")]
    [InlineData("CREATE FUNCTION udfProductInYear (@model_year INT) RETURNS TABLE AS RETURN SELECT product_name, model_year, list_price FROM production.products WHERE model_year = @model_year")]
    public void Native_ddl_round_trips(string sql) => TSqlMutationCoreTests.RoundTrip(sql);

    [Fact]
    public void Identity_and_key_details_are_structural()
    {
        var create = Assert.IsType<CreateTableStatement>(Assert.Single(SqlParser.Parse(
            "CREATE TABLE t (id INT IDENTITY(10, 2) CONSTRAINT pk PRIMARY KEY NONCLUSTERED, a INT CONSTRAINT df DEFAULT 4)",
            SqlDialects.TSql).Statements));
        var id = Assert.IsType<ColumnDefinition>(create.Elements[0]);
        Assert.Equal(IdentityGeneration.ByDefault, id.Identity);
        Assert.Equal("10", id.IdentitySeed!.ToSql());
        Assert.Equal("2", id.IdentityIncrement!.ToSql());
        Assert.Equal(IndexClustering.Nonclustered, id.Clustering);
        Assert.Equal("pk", id.KeyConstraintName!.Value);
        var rewritten = Assert.IsType<CreateTableStatement>(new RenameRewriter().Visit(create));
        Assert.Equal("renamed", Assert.IsType<ColumnDefinition>(rewritten.Elements[1]).DefaultConstraintName!.Value);
        Assert.Contains(create.FindAll<SqlIdentifier>(), identifier => identifier.Value == "df");
        var changedNumbers = Assert.IsType<CreateTableStatement>(new NumberRewriter().Visit(create));
        var changedIdentity = Assert.IsType<ColumnDefinition>(changedNumbers.Elements[0]);
        Assert.Equal("11", changedIdentity.IdentitySeed!.ToSql());
        Assert.Equal("3", changedIdentity.IdentityIncrement!.ToSql());
    }

    [Fact]
    public void Native_identity_and_add_do_not_change_standard_generation()
    {
        var column = new ColumnDefinition(new("id"), new SqlDataType("INT"), Identity: IdentityGeneration.ByDefault);
        var create = new CreateTableStatement(new("t"), [column]);
        Assert.Contains("IDENTITY", create.ToSql(SqlDialects.TSql));
        Assert.DoesNotContain("GENERATED", create.ToSql(SqlDialects.TSql));
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", create.ToSql(SqlDialects.PostgreSql));
        var alter = new AlterTableStatement(new("t"), [new AddColumnAction(column)]);
        Assert.Contains("ADD id", alter.ToSql(SqlDialects.TSql));
        Assert.Contains("ADD COLUMN", alter.ToSql(SqlDialects.PostgreSql));
        Assert.Throws<NotSupportedException>(() =>
            (create with { Elements = [column with { Identity = IdentityGeneration.Always }] }).ToSql(SqlDialects.TSql));
    }

    [Fact]
    public void Inline_function_body_and_parameters_are_visited()
    {
        var function = Assert.IsType<CreateInlineFunctionStatement>(Assert.Single(SqlParser.Parse(
            "CREATE FUNCTION dbo.f(@id INT) RETURNS TABLE AS RETURN SELECT @id AS id", SqlDialects.TSql).Statements));
        Assert.Single(function.Parameters);
        Assert.Single(function.FindAll<SelectStatement>());
        Assert.Single(function.FindAll<ProcedureParameter>());
        Assert.Single(function.FindAll<LocalVariableExpression>());
        Assert.Throws<NotSupportedException>(() => function.ToSql(SqlDialects.PostgreSql));
    }

    [Fact]
    public void Inline_function_and_ddl_builders_round_trip()
    {
        var function = Sql.CreateInlineFunction("dbo.f").Parameter("id", new SqlDataType("INT"))
            .Returns(Sql.SelectItems(new SelectItem(Sql.Lit(1), "value")).Build()).Build();
        TSqlMutationCoreTests.RoundTrip(function.ToSql(SqlDialects.TSql));
        TSqlMutationCoreTests.RoundTrip(Sql.CreateView("v").OrAlter().As(Sql.Select("id").From("t").Build()).ToSql(SqlDialects.TSql));
        TSqlMutationCoreTests.RoundTrip(Sql.CreateIndex("ix", "t").Clustering(IndexClustering.Nonclustered).Column("id").ToSql(SqlDialects.TSql));
        TSqlMutationCoreTests.RoundTrip(Sql.AlterTable("t").AlterColumnType("id", new SqlDataType("INT"), Nullability.NotNull).ToSql(SqlDialects.TSql));
    }

    [Fact]
    public void Inline_function_parameters_have_isolated_schema_types()
    {
        var catalog = new SqlSchemaCatalog();
        var options = new SqlSchemaValidationOptions { CheckTypes = true };
        var valid = SqlValidator.Validate(
            "CREATE FUNCTION f(@id INT) RETURNS TABLE AS RETURN SELECT @id + 1 AS id", catalog, SqlDialects.TSql, options);
        Assert.True(valid.IsValid, string.Join("\n", valid.Diagnostics.Select(d => d.Message)));
        var invalid = SqlValidator.Validate(
            "CREATE FUNCTION f(@id INT) RETURNS TABLE AS RETURN SELECT @id + 'text' AS id", catalog, SqlDialects.TSql, options);
        Assert.False(invalid.IsValid);
    }

    [Fact]
    public void Plain_schema_is_structural_and_builder_equivalent()
    {
        var schema = Assert.IsType<CreateSchemaStatement>(Assert.Single(
            SqlParser.Parse("CREATE SCHEMA df", SqlDialects.TSql).Statements));
        Assert.Equal("df", Assert.Single(schema.FindAll<SqlIdentifier>()).Value);
        Assert.Same(schema, new NumberRewriter().Visit(schema));
        Assert.Equal("renamed", Assert.IsType<CreateSchemaStatement>(new RenameRewriter().Visit(schema)).Name.Value);
        var visitor = new SchemaVisitor();
        visitor.Visit(schema);
        Assert.True(visitor.Visited);
        Assert.Equal(schema.ToSql(SqlDialects.TSql), Sql.CreateSchema("df").ToSql(SqlDialects.TSql));
        Assert.True(SqlValidator.Validate("CREATE SCHEMA testSchema", new SqlSchemaCatalog(), SqlDialects.TSql).IsValid);
        foreach (var dialect in new[] { SqlDialects.Generic, SqlDialects.PostgreSql, SqlDialects.MySql, SqlDialects.Sqlite, SqlDialects.Oracle })
        {
            Assert.Throws<NotSupportedException>(() => schema.ToSql(dialect));
            Assert.False(SqlParser.TryParse("CREATE SCHEMA testSchema", dialect, out _, out _));
        }
        Assert.Throws<ArgumentException>(() => Sql.CreateSchema(" "));
    }

    [Theory]
    [InlineData("CREATE SCHEMA testSchema AUTHORIZATION dbo")]
    [InlineData("CREATE SCHEMA AUTHORIZATION dbo")]
    [InlineData("CREATE SCHEMA testSchema CREATE TABLE t (id INT)")]
    [InlineData("CREATE SCHEMA testSchema CREATE VIEW v AS SELECT 1 AS id")]
    [InlineData("CREATE SCHEMA testSchema GRANT SELECT ON t TO public")]
    [InlineData("CREATE SCHEMA dbo.testSchema")]
    public void Schema_security_and_elements_are_not_accepted(string sql) =>
        Assert.False(SqlParser.TryParse(sql, SqlDialects.TSql, out _, out _));

    private sealed class SchemaVisitor : SqlVisitor
    {
        public bool Visited { get; private set; }
        protected override void VisitCreateSchema(CreateSchemaStatement node)
        {
            Visited = true;
            base.VisitCreateSchema(node);
        }
    }

    private sealed class RenameRewriter : SqlRewriter
    {
        protected override SqlNode VisitIdentifier(SqlIdentifier node) =>
            node.Value == "df" ? node with { Value = "renamed" } : node;
    }

    private sealed class NumberRewriter : SqlRewriter
    {
        protected override SqlNode VisitLiteral(LiteralExpression node) =>
            node.Value is int value ? node with { Value = value + 1 } :
            node.Value is long longValue ? node with { Value = longValue + 1 } : node;
    }
}
