<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageId>Cyqwel</PackageId>
    <Description>Fast, extensible SQL parsing, transformation, generation, and builder utilities for .NET.</Description>
    <Authors>Sébastien Ros</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/sebastienros/cyqwel</RepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Parlot" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
